export interface Region {
  id: number;
  nombre: string;
  idDepartamento?: number;
}

export const paises = ["Honduras"];

export const departm = [
  { id: 1, nombre: "Atlántida" },
  { id: 2, nombre: "Choluteca" },
  { id: 3, nombre: "Colón" },
  { id: 4, nombre: "Comayagua" },
  { id: 5, nombre: "Copán" },
  { id: 6, nombre: "Cortés" },
  { id: 7, nombre: "El Paraíso" },
  { id: 8, nombre: "Francisco Morazán" },
  { id: 9, nombre: "Gracias a Dios" },
  { id: 10, nombre: "Intibucá" },
  { id: 11, nombre: "Islas de la Bahía" },
  { id: 12, nombre: "La Paz" },
  { id: 13, nombre: "Lempira" },
  { id: 14, nombre: "Ocotepeque" },
  { id: 15, nombre: "Olancho" },
  { id: 16, nombre: "Santa Bárbara" },
  { id: 17, nombre: "Valle" },
  { id: 18, nombre: "Yoro" },
];

export const munic = [
  // Atlántida
  { id: 1, nombre: "Arizona", idDepartamento: 1 },
  { id: 2, nombre: "El Porvenir", idDepartamento: 1 },
  { id: 3, nombre: "Esparta", idDepartamento: 1 },
  { id: 4, nombre: "Jutiapa", idDepartamento: 1 },
  { id: 5, nombre: "La Masica", idDepartamento: 1 },
  { id: 6, nombre: "San Francisco", idDepartamento: 1 },
  { id: 7, nombre: "Tela", idDepartamento: 1 },
  // Choluteca
  { id: 8, nombre: "Arizona", idDepartamento: 2 },
  { id: 9, nombre: "Choluteca", idDepartamento: 2 },
  { id: 10, nombre: "Concepción de María", idDepartamento: 2 },
  { id: 11, nombre: "Duyure", idDepartamento: 2 },
  { id: 12, nombre: "El Corpus", idDepartamento: 2 },
  { id: 13, nombre: "El Triunfo", idDepartamento: 2 },
  { id: 14, nombre: "Marcovia", idDepartamento: 2 },
  { id: 15, nombre: "Morolica", idDepartamento: 2 },
  { id: 16, nombre: "Namasigüe", idDepartamento: 2 },
  { id: 17, nombre: "Orocuina", idDepartamento: 2 },
  { id: 18, nombre: "Pespire", idDepartamento: 2 },
  { id: 19, nombre: "San Antonio de Flores", idDepartamento: 2 },
  { id: 20, nombre: "San Isidro", idDepartamento: 2 },
  { id: 21, nombre: "San José", idDepartamento: 2 },
  { id: 22, nombre: "San Marcos de Colón", idDepartamento: 2 },
  { id: 23, nombre: "Santa Ana de Yusguare", idDepartamento: 2 },
  // Colón
  { id: 24, nombre: "Apacilagua", idDepartamento: 3 },
  { id: 25, nombre: "Arada", idDepartamento: 3 },
  { id: 26, nombre: "Dulce Nombre de Culmí", idDepartamento: 3 },
  { id: 27, nombre: "Iriona", idDepartamento: 3 },
  { id: 28, nombre: "Janos", idDepartamento: 3 },
  { id: 29, nombre: "Limón", idDepartamento: 3 },
  { id: 30, nombre: "Saba", idDepartamento: 3 },
  { id: 31, nombre: "Santa Fe", idDepartamento: 3 },
  { id: 32, nombre: "Sonaguera", idDepartamento: 3 },
  { id: 33, nombre: "Tocoa", idDepartamento: 3 },
  // Comayagua
  { id: 34, nombre: "Bonito Oriental", idDepartamento: 4 },
  { id: 35, nombre: "Comayagua", idDepartamento: 4 },
  { id: 36, nombre: "Ajuterique", idDepartamento: 4 },
  { id: 37, nombre: "El Rosario", idDepartamento: 4 },
  { id: 38, nombre: "Esquías", idDepartamento: 4 },
  { id: 39, nombre: "Humuya", idDepartamento: 4 },
  { id: 40, nombre: "La Libertad", idDepartamento: 4 },
  { id: 41, nombre: "Lamaní", idDepartamento: 4 },
  { id: 42, nombre: "La Trinidad", idDepartamento: 4 },
  { id: 43, nombre: "Lejamaní", idDepartamento: 4 },
  { id: 44, nombre: "Meámbar", idDepartamento: 4 },
  { id: 45, nombre: "Minas de Oro", idDepartamento: 4 },
  { id: 46, nombre: "Ojos de Agua", idDepartamento: 4 },
  { id: 47, nombre: "San Jerónimo", idDepartamento: 4 },
  { id: 48, nombre: "San José de Comayagua", idDepartamento: 4 },
  { id: 49, nombre: "San José del Potrero", idDepartamento: 4 },
  { id: 50, nombre: "San Luis", idDepartamento: 4 },
  { id: 51, nombre: "San Sebastián", idDepartamento: 4 },
  { id: 52, nombre: "Siguatepeque", idDepartamento: 4 },
  { id: 53, nombre: "Taulabé", idDepartamento: 4 },
  { id: 54, nombre: "Villa de San Antonio", idDepartamento: 4 },
  { id: 55, nombre: "Las Lajas", idDepartamento: 4 },
  // Municipios de Copán
  { id: 56, nombre: "Santa Rosa de Copán", idDepartamento: 5 },
  { id: 57, nombre: "Cabañas", idDepartamento: 5 },
  { id: 58, nombre: "Concepción", idDepartamento: 5 },
  { id: 59, nombre: "Copán Ruinas", idDepartamento: 5 },
  { id: 60, nombre: "Corquín", idDepartamento: 5 },
  { id: 61, nombre: "Cucuyagua", idDepartamento: 5 },
  { id: 62, nombre: "Dolores", idDepartamento: 5 },
  { id: 63, nombre: "Dulce Nombre", idDepartamento: 5 },
  { id: 64, nombre: "El Paraíso", idDepartamento: 5 },
  { id: 65, nombre: "Florida", idDepartamento: 5 },
  { id: 66, nombre: "La Jigua", idDepartamento: 5 },
  { id: 67, nombre: "La Unión", idDepartamento: 5 },
  { id: 68, nombre: "Nueva Arcadia", idDepartamento: 5 },
  { id: 69, nombre: "San Agustín", idDepartamento: 5 },
  { id: 70, nombre: "San Antonio", idDepartamento: 5 },
  { id: 71, nombre: "San Jerónimo", idDepartamento: 5 },
  { id: 72, nombre: "San José", idDepartamento: 5 },

  //cortes
  { id: 73, nombre: "Puerto Cortés", idDepartamento: 6 },
  { id: 74, nombre: "San Pedro Sula", idDepartamento: 6 },
  { id: 75, nombre: "Choloma", idDepartamento: 6 },
  { id: 76, nombre: "Villanueva", idDepartamento: 6 },
  { id: 77, nombre: "La Lima", idDepartamento: 6 },
  { id: 78, nombre: "Pimienta", idDepartamento: 6 },
  { id: 79, nombre: "Potrerillos", idDepartamento: 6 },
  { id: 80, nombre: "Santa Cruz de Yojoa", idDepartamento: 6 },
  { id: 81, nombre: "Omoa", idDepartamento: 6 },

  //el paraiso
  { id: 82, nombre: "Yuscarán", idDepartamento: 7 },
  { id: 83, nombre: "Alauca", idDepartamento: 7 },
  { id: 84, nombre: "Danlí", idDepartamento: 7 },
  { id: 85, nombre: "Trojes", idDepartamento: 7 },
  { id: 86, nombre: "Texiguat", idDepartamento: 7 },
  { id: 87, nombre: "Vado Ancho", idDepartamento: 7 },
  { id: 88, nombre: "Sabanagrande", idDepartamento: 7 },
  { id: 89, nombre: "Guinope", idDepartamento: 7 },
  { id: 90, nombre: "Jacaleapa", idDepartamento: 7 },
  { id: 91, nombre: "Liure", idDepartamento: 7 },
  { id: 92, nombre: "Morocelí", idDepartamento: 7 },
  { id: 93, nombre: "Oropoli", idDepartamento: 7 },
  { id: 94, nombre: "Potrerillos", idDepartamento: 7 },
  { id: 95, nombre: "San Antonio de Flores", idDepartamento: 7 },
  { id: 96, nombre: "San Lucas", idDepartamento: 7 },
  { id: 97, nombre: "San Matías", idDepartamento: 7 },
  { id: 98, nombre: "Soledad", idDepartamento: 7 },
  { id: 99, nombre: "Teupasenti", idDepartamento: 7 },
  { id: 100, nombre: "Texistepeque", idDepartamento: 7 },

  //Francisco Morazán
  { id: 101, nombre: "Distrito Central", idDepartamento: 8 },
  { id: 102, nombre: "Alubarén", idDepartamento: 8 },
  { id: 103, nombre: "Cedros", idDepartamento: 8 },
  { id: 104, nombre: "Curarén", idDepartamento: 8 },
  { id: 105, nombre: "El Porvenir", idDepartamento: 8 },
  { id: 106, nombre: "Guaimaca", idDepartamento: 8 },
  { id: 107, nombre: "La Libertad", idDepartamento: 8 },
  { id: 108, nombre: "La Venta", idDepartamento: 8 },
  { id: 109, nombre: "Lepaterique", idDepartamento: 8 },
  { id: 110, nombre: "Maraita", idDepartamento: 8 },
  { id: 111, nombre: "Marale", idDepartamento: 8 },
  { id: 112, nombre: "Nueva Armenia", idDepartamento: 8 },
  { id: 113, nombre: "Ojojona", idDepartamento: 8 },
  { id: 114, nombre: "Orica", idDepartamento: 8 },
  { id: 115, nombre: "Reitoca", idDepartamento: 8 },
  { id: 116, nombre: "Sabanagrande", idDepartamento: 8 },
  { id: 117, nombre: "San Antonio de Oriente", idDepartamento: 8 },
  { id: 118, nombre: "San Buenaventura", idDepartamento: 8 },
  { id: 119, nombre: "San Ignacio", idDepartamento: 8 },
  { id: 120, nombre: "San Juan de Flores", idDepartamento: 8 },
  { id: 121, nombre: "San Miguelito", idDepartamento: 8 },
  { id: 122, nombre: "Santa Ana", idDepartamento: 8 },
  { id: 123, nombre: "Santa Lucía", idDepartamento: 8 },
  { id: 124, nombre: "Talanga", idDepartamento: 8 },
  { id: 125, nombre: "Tatumbla", idDepartamento: 8 },
  { id: 126, nombre: "Valle de Ángeles", idDepartamento: 8 },
  { id: 127, nombre: "Villa de San Francisco", idDepartamento: 8 },
  { id: 128, nombre: "Vallecillo", idDepartamento: 8 },

  // graciasDios
  { id: 129, nombre: "Puerto Lempira", idDepartamento: 9 },
  { id: 130, nombre: "Brus Laguna", idDepartamento: 9 },
  { id: 131, nombre: "Ahuas", idDepartamento: 9 },
  { id: 132, nombre: "Juan Francisco Bulnes", idDepartamento: 9 },
  { id: 133, nombre: "Ramón Villeda Morales", idDepartamento: 9 },

  // Municipios de Intibucá

  { id: 134, nombre: "La Esperanza", idDepartamento: 10 },
  { id: 135, nombre: "Camasca", idDepartamento: 10 },
  { id: 136, nombre: "Colomoncagua", idDepartamento: 10 },
  { id: 137, nombre: "Concepción", idDepartamento: 10 },
  { id: 138, nombre: "Dolores", idDepartamento: 10 },
  { id: 139, nombre: "Intibucá", idDepartamento: 10 },
  { id: 140, nombre: "Jesús de Otoro", idDepartamento: 10 },
  { id: 141, nombre: "Magdalena", idDepartamento: 10 },
  { id: 142, nombre: "Masaguara", idDepartamento: 10 },
  { id: 143, nombre: "San Antonio", idDepartamento: 10 },
  { id: 144, nombre: "San Francisco de Opalaca", idDepartamento: 10 },
  { id: 145, nombre: "San Isidro", idDepartamento: 10 },
  { id: 146, nombre: "San Juan", idDepartamento: 10 },
  { id: 147, nombre: "San Marcos de la Sierra", idDepartamento: 10 },
  { id: 148, nombre: "San Miguelito", idDepartamento: 10 },
  { id: 149, nombre: "Santa Lucía", idDepartamento: 10 },
  { id: 150, nombre: "Yamaranguila", idDepartamento: 10 },

  // Municipios de Islas de la Bahía

  { id: 151, nombre: "Roatán", idDepartamento: 11 },
  { id: 152, nombre: "José Santos Guardiola", idDepartamento: 11 },
  { id: 153, nombre: "Guanaja", idDepartamento: 11 },
  { id: 154, nombre: "Utila", idDepartamento: 11 },

  //la paz
  { id: 155, nombre: "La Paz", idDepartamento: 12 },
  { id: 156, nombre: "Aguanqueterique", idDepartamento: 12 },
  { id: 157, nombre: "Cabañas", idDepartamento: 12 },
  { id: 158, nombre: "Cane", idDepartamento: 12 },
  { id: 159, nombre: "Chinacla", idDepartamento: 12 },
  { id: 160, nombre: "Guajiquiro", idDepartamento: 12 },
  { id: 161, nombre: "Lauterique", idDepartamento: 12 },
  { id: 162, nombre: "Marcala", idDepartamento: 12 },
  { id: 163, nombre: "Mercedes de Oriente", idDepartamento: 12 },
  { id: 164, nombre: "Opatoro", idDepartamento: 12 },
  { id: 165, nombre: "San Antonio del Norte", idDepartamento: 12 },
  { id: 166, nombre: "San José", idDepartamento: 12 },
  { id: 167, nombre: "San Juan", idDepartamento: 12 },
  { id: 168, nombre: "San Pedro de Tutule", idDepartamento: 12 },
  { id: 169, nombre: "Santa Ana", idDepartamento: 12 },
  { id: 170, nombre: "Santa Elena", idDepartamento: 12 },
  { id: 171, nombre: "Santa María", idDepartamento: 12 },
  { id: 172, nombre: "Santiago de Puringla", idDepartamento: 12 },
  { id: 173, nombre: "Yarula", idDepartamento: 12 },

  // Municipios de Lempira

  { id: 174, nombre: "Gracias", idDepartamento: 13 },
  { id: 175, nombre: "La Campa", idDepartamento: 13 },
  { id: 176, nombre: "La Iguala", idDepartamento: 13 },
  { id: 177, nombre: "Las Flores", idDepartamento: 13 },
  { id: 178, nombre: "Lepaera", idDepartamento: 13 },
  { id: 179, nombre: "Mapulaca", idDepartamento: 13 },
  { id: 180, nombre: "Piraera", idDepartamento: 13 },
  { id: 181, nombre: "San Andrés", idDepartamento: 13 },
  { id: 182, nombre: "San Francisco", idDepartamento: 13 },
  { id: 183, nombre: "San Juan Guarita", idDepartamento: 13 },
  { id: 184, nombre: "San Manuel Colohete", idDepartamento: 13 },
  { id: 185, nombre: "San Marcos de Caiquín", idDepartamento: 13 },
  { id: 186, nombre: "San Rafael", idDepartamento: 13 },
  { id: 187, nombre: "Santa Cruz", idDepartamento: 13 },
  { id: 188, nombre: "Talgua", idDepartamento: 13 },
  { id: 189, nombre: "Tambla", idDepartamento: 13 },
  { id: 190, nombre: "Tomalá", idDepartamento: 13 },
  { id: 191, nombre: "Valladolid", idDepartamento: 13 },
  { id: 192, nombre: "Virginia", idDepartamento: 13 },

  // Municipios de Ocotepeque

  { id: 193, nombre: "Belén Gualcho", idDepartamento: 14 },
  { id: 194, nombre: "Concepción", idDepartamento: 14 },
  { id: 195, nombre: "Dolores Merendón", idDepartamento: 14 },
  { id: 196, nombre: "Fraternidad", idDepartamento: 14 },
  { id: 197, nombre: "La Encarnación", idDepartamento: 14 },
  { id: 198, nombre: "La Labor", idDepartamento: 14 },
  { id: 199, nombre: "Lucerna", idDepartamento: 14 },
  { id: 200, nombre: "Mercedes", idDepartamento: 14 },
  { id: 201, nombre: "San Fernando", idDepartamento: 14 },
  { id: 202, nombre: "San Francisco del Valle", idDepartamento: 14 },
  { id: 203, nombre: "San Jorge", idDepartamento: 14 },
  { id: 204, nombre: "San Marcos", idDepartamento: 14 },
  { id: 205, nombre: "Santa Fe", idDepartamento: 14 },
  { id: 206, nombre: "Sensenti", idDepartamento: 14 },
  { id: 207, nombre: "Sinuapa", idDepartamento: 14 },

  //Olancho
  { id: 208, nombre: "Juticalpa", idDepartamento: 15 },
  { id: 209, nombre: "Campamento", idDepartamento: 15 },
  { id: 210, nombre: "Catacamas", idDepartamento: 15 },
  { id: 211, nombre: "Concordia", idDepartamento: 15 },
  { id: 212, nombre: "Dulce Nombre de Culmí", idDepartamento: 15 },
  { id: 213, nombre: "El Rosario", idDepartamento: 15 },
  { id: 214, nombre: "Esquipulas del Norte", idDepartamento: 15 },
  { id: 215, nombre: "Gualaco", idDepartamento: 15 },
  { id: 216, nombre: "Guarizama", idDepartamento: 15 },
  { id: 217, nombre: "Guata", idDepartamento: 15 },
  { id: 218, nombre: "Guayape", idDepartamento: 15 },
  { id: 219, nombre: "Jano", idDepartamento: 15 },
  { id: 220, nombre: "La Unión", idDepartamento: 15 },
  { id: 221, nombre: "Mangulile", idDepartamento: 15 },
  { id: 222, nombre: "Manto", idDepartamento: 15 },
  { id: 223, nombre: "Salamá", idDepartamento: 15 },
  { id: 224, nombre: "San Esteban", idDepartamento: 15 },
  { id: 225, nombre: "San Francisco de Becerra", idDepartamento: 15 },
  { id: 226, nombre: "San Francisco de La Paz", idDepartamento: 15 },
  { id: 227, nombre: "Santa María del Real", idDepartamento: 15 },
  { id: 228, nombre: "Silca", idDepartamento: 15 },
  { id: 229, nombre: "Yocón", idDepartamento: 15 },

  // Municipios de Santa Bárbara

  { id: 230, nombre: "Santa Bárbara", idDepartamento: 16 },
  { id: 231, nombre: "Arada", idDepartamento: 16 },
  { id: 232, nombre: "Atima", idDepartamento: 16 },
  { id: 233, nombre: "Azacualpa", idDepartamento: 16 },
  { id: 234, nombre: "Ceguaca", idDepartamento: 16 },
  { id: 235, nombre: "Concepción del Norte", idDepartamento: 16 },
  { id: 236, nombre: "Concepción del Sur", idDepartamento: 16 },
  { id: 237, nombre: "Chinda", idDepartamento: 16 },
  { id: 238, nombre: "El Níspero", idDepartamento: 16 },
  { id: 239, nombre: "Gualala", idDepartamento: 16 },
  { id: 240, nombre: "Ilama", idDepartamento: 16 },
  { id: 241, nombre: "Macuelizo", idDepartamento: 16 },
  { id: 242, nombre: "Naranjito", idDepartamento: 16 },
  { id: 243, nombre: "Nuevo Celilac", idDepartamento: 16 },
  { id: 244, nombre: "Petoa", idDepartamento: 16 },
  { id: 245, nombre: "Protección", idDepartamento: 16 },
  { id: 246, nombre: "Quimistán", idDepartamento: 16 },
  { id: 247, nombre: "San Francisco de Ojuera", idDepartamento: 16 },
  { id: 248, nombre: "San Luis", idDepartamento: 16 },
  { id: 249, nombre: "San Marcos", idDepartamento: 16 },
  { id: 250, nombre: "San Nicolás", idDepartamento: 16 },
  { id: 251, nombre: "San Pedro Zacapa", idDepartamento: 16 },
  { id: 252, nombre: "Santa Rita", idDepartamento: 16 },
  { id: 253, nombre: "San Vicente Centenario", idDepartamento: 16 },
  { id: 254, nombre: "Trinidad", idDepartamento: 16 },

  // Municipios de Valle

  { id: 255, nombre: "Nacaome", idDepartamento: 17 },
  { id: 256, nombre: "Alianza", idDepartamento: 17 },
  { id: 257, nombre: "Amapala", idDepartamento: 17 },
  { id: 258, nombre: "Aramecina", idDepartamento: 17 },
  { id: 259, nombre: "Caridad", idDepartamento: 17 },
  { id: 260, nombre: "Goascorán", idDepartamento: 17 },
  { id: 261, nombre: "Langue", idDepartamento: 17 },
  { id: 262, nombre: "San Francisco de Coray", idDepartamento: 17 },
  { id: 263, nombre: "San Lorenzo", idDepartamento: 17 },

  // Municipios de Yoro

  { id: 264, nombre: "Yoro", idDepartamento: 18 },
  { id: 265, nombre: "Arenal", idDepartamento: 18 },
  { id: 266, nombre: "El Negrito", idDepartamento: 18 },
  { id: 267, nombre: "Victoria", idDepartamento: 18 },
  { id: 268, nombre: "Morazán", idDepartamento: 18 },
  { id: 269, nombre: "Olanchito", idDepartamento: 18 },
  { id: 270, nombre: "Santa Rita", idDepartamento: 18 },
  { id: 271, nombre: "Sulaco", idDepartamento: 18 },
  { id: 272, nombre: "Yorito", idDepartamento: 18 },
  { id: 273, nombre: "Francisco Morazán", idDepartamento: 18 },
  { id: 274, nombre: "Jocón", idDepartamento: 18 },
  { id: 275, nombre: "Morazán", idDepartamento: 18 },
  { id: 276, nombre: "Sulaco", idDepartamento: 18 },
  { id: 277, nombre: "Victoria", idDepartamento: 18 },
];